# Generated by Django 3.0.3 on 2020-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='currentmoney',
            field=models.BigIntegerField(default=0),
        ),
    ]
