# Generated by Django 3.0.3 on 2020-05-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200523_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
